#!/bin/bash

# Shortcut for mvn scala:run -Dlauncher=... -DaddArgs=...
# Example:
# lookup> ./run LAUNCHER ARG1 ARG2 ARG3
# is equivalent to
# lookup> mvn scala:run "-Dlauncher=LAUNCHER" "-DaddArgs=ARG1|ARG2|ARG3"

LAUNCHER="$1"

ADD_ARGS="$2"
for ARG in ${@:3}
do
  ADD_ARGS="$ADD_ARGS|$ARG"
done

mvn scala:run "-Dlauncher=$LAUNCHER" "-DaddArgs=$ADD_ARGS" -Dmaven.test.skip=true 
