FROM java:8

MAINTAINER  DBpedia Team <dbpedia-developers@lists.sourceforge.net>

RUN apt-get update && apt-get install -y \
    curl

ENV INDEX_URL  wifo5-04.informatik.uni-mannheim.de/downloads/
ENV INDEX_FILENAME dbpedia-lookup-index-3.8.tgz

ENV LOOKUP_JAR dbpedia-lookup-3.1-jar-with-dependencies.jar
ENV LOOKUP_URL oss.sonatype.org/content/groups/public/org/dbpedia/lookup/dbpedia-lookup/3.1/

RUN mkdir -p /opt/lookup && \
    cd /opt/lookup && \
    curl -O "http://$LOOKUP_URL/$LOOKUP_JAR" && \
    curl -O "http://$INDEX_URL/$INDEX_FILENAME" && \
    tar xvf $INDEX_FILENAME   && \
    rm  $INDEX_FILENAME

EXPOSE 1111
